modLoader = "javafml"
loaderVersion = "[47,)"
issueTrackerURL = "https://github.com/TechTastic/Inline-LaTeX/issues"
license = "MIT"

[[mods]]
modId = "inlinelatex"
version = "${version}"
displayName = "Inline: LaTeX"
authors = "TechTastic"
description = '''
Adding LaTeX support to Inline!
'''
logoFile = "icon.png"

[[dependencies.inlinelatex]]
modId = "forge"
mandatory = true
versionRange = "[47,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.inlinelatex]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.inlinelatex]]
modId = "architectury"
mandatory = true
versionRange = "[9.2.14,)"
ordering = "AFTER"
side = "BOTH"

[[dependencies.inlinelatex]]
modId = "inline"
mandatory = true
versionRange = "[1.2.2,)"
ordering = "AFTER"
side = "BOTH"
